name: get
on:
  push:
    paths:
      - 'dl/*'
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Execute
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          first_filepath=$(git diff --name-only "$GITHUB_SHA" "$GITHUB_SHA"^ | head -n 1)
          url=$(echo -n "$first_filepath" | base64 -d)
          curl "$url" -o $first_filepath
          git add .
          git commit -m "[skip ci]"
          git push -f origin main
