name: get
on:
  push:
    paths:
      - 'dl/*'
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Execute
        run: |
          cd dl
          first_filename=$(git diff --name-only "$GITHUB_SHA" "$GITHUB_SHA"^ | head -n 1)
          filename=$(echo -n "$first_filename" | base64 -w0)
          wget "$filename"
          cd ..
