name: get
on:
  push:
    paths:
      - 'cmd'
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Execute
        run: |
          curl -o cmd_ $(cat cmd | base64 -w0 -d)
          mv cmd_ cmd
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add cmd
          git commit -m "[skip ci]"
          git push -f origin main
